### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no netty_tcnative_osx_x86_64 in java.library.path

### ISSUE THREAD

**Issue by mingxing47** [netty/netty-tcnative#331]
hi
When I add netty-tcnative-boringssl-static 2.0.7.Final in the pom file, and run my program, the console shows that:

`
java.lang.UnsatisfiedLinkError: no netty_tcnative_osx_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:229)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:221)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:207)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:118)
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:82)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:419)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:89)
	at io.netty.handler.ssl.SslContext.defaultProvider(SslContext.java:118)
	at io.netty.handler.ssl.SslContext.defaultServerProvider(SslContext.java:105)
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:407)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:441)
	at com.yunanbao.yunxiazi.proxy.servers.h5login.H5loginServer.run(H5loginServer.java:55)
	at com.yunanbao.yunxiazi.proxy.servers.h5login.H5loginServer.main(H5loginServer.java:88)
02-28 18:39:13.648 [main] DEBUG i.n.u.internal.NativeLibraryLoader [debug] [86] - netty_tcnative_osx_x86_64 cannot be loaded from java.libary.path, now trying export to -Dio.netty.native.workdir: /var/folders/cg/8__zm_7x70bdzbpyv_sf8z3m0000gn/T
`

Please tell me where and How can I get the netty_tcnative_osx_x86_64 file?
thx~

**Comment by dfeng99** [comment]
Well, I found that netty-tcnative will automatically extract a shared library so file into a tmp dir if it eventually can't find the shared library. Just curious about why not simply copy the so into the right path?

**Comment by normanmaurer** [comment]
I think this is fixed in latest release of netty / netty-tcnative. Please reopen if you still think there is an issue

**Comment by oubiwann** [comment]
@normanmaurer wrt "latest", are you referring to `2.0.12.Final`?

I have that version in my dependencies but am still seeing this error on my Mac (and last I checked, not on my Linux machine).

I'm going to run with `-versbose:class` to make sure I'm not pulling in an older version; if that looks okay, I'll reopen this issue ...

**Comment by oubiwann** [comment]
Ah ... there are two stack traces in the logs (one preceded by 
```
Unable to load the library 'netty_tcnative_osx_x86_64', trying other loading mechanism.
``` 
and the other preceded by 
```
netty_tcnative_osx_x86_64 cannot be loaded from java.libary.path, now trying export to -Dio.netty.native.workdir ...
```

However, after those, I do see a successful load:
```
Successfully loaded the library /.../libnetty_tcnative_osx_x86_646414635283876674468.dylib
```

(Seems like it might be more appropriate to have those in a `TRACE` log rather than `DEBUG` ...)

Not reopening ticket ...

**Comment by jonafer11** [comment]
I think it's because it can not load the full name. The error says that it does not load netty_tcnative_osx_x86_64 but the file it generates is called netty_tcnative_osx_x86_646414635283876674468.dylib

**Comment by master-starcloud** [comment]
yeah, thanks for oubiwann and I read the source code io.netty.util.internal.NativeLibraryLoader#load.
it solved my problem

**Comment by xinln** [comment]
java.lang.UnsatisfiedLinkError: no org_apache_pulsar_shade_netty_tcnative_windows_x86_64 in java.library.path

我出现了这个错， 请问楼主解决了么

**Comment by oubiwann** [comment]
@xinln Be sure to read all the log output ... after the error you mentioned, do you see a line a little bit later in the log output that says `Successfully loaded the library`?

In the past, when I've had problems starting one of my apps that used netty, the error above was not the cause ... the errors in the logs are easy to misinterpret. I'm not saying the same is true for you, but it _might_ be ;-)

**Comment by marcelloromani** [comment]
> (Seems like it might be more appropriate to have those in a `TRACE` log rather than `DEBUG` ...)

I totally second that!

**Comment by NoComments** [comment]
same error to me,how to resovle it

**Comment by NoComments** [comment]
same error to me,how to resovle it

**Comment by metayx** [comment]
@NoComments 解决了吗老哥

**Comment by mohamedanees6** [comment]
@NoComments  I fixed it by moving from Alpine Linux to CentOS.

**Comment by liangliangoo** [comment]
> @NoComments 解决了吗老哥
我也想知道

**Comment by gm100861** [comment]
same error to me,how to resovle it

**Comment by phial3** [comment]
```java
Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_aarch_64
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
		... 38 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_aarch_64.jnilib
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:181)
		... 39 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_aarch_64 in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
			at java.lang.Runtime.loadLibrary0(Runtime.java:872)
			at java.lang.System.loadLibrary(System.java:1124)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
			... 39 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_aarch_64 in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
				at java.lang.Runtime.loadLibrary0(Runtime.java:872)
				at java.lang.System.loadLibrary(System.java:1124)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
				... 40 more
```

how to resolve ?

**Comment by Leelaprasadreddykanchi** [comment]
java.lang.UnsatisfiedLinkError: no netty_tcnative_windows_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1863)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1122)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:578)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:133)
	at io.gatling.http.util.SslContextsFactory.<init>(SslContexts.scala:55)
	at io.gatling.http.engine.HttpEngine$.apply(HttpEngine.scala:47)
	at io.gatling.http.protocol.HttpProtocol$$anon$1.newComponents(HttpProtocol.scala:55)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$1(Protocol.scala:68)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.componentsFactory$1(Protocol.scala:68)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.comps$1(Protocol.scala:71)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$4(Protocol.scala:73)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.components(Protocol.scala:73)
	at io.gatling.http.action.HttpActionBuilder.lookUpHttpComponents(HttpActionBuilder.scala:26)
	at io.gatling.http.action.HttpRequestActionBuilder.build(HttpRequestActionBuilder.scala:33)
	at io.gatling.core.structure.BuildAction.$anonfun$build$1(BuildAction.scala:28)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at io.gatling.core.structure.BuildAction.build(BuildAction.scala:27)
	at io.gatling.core.structure.BuildAction.build$(BuildAction.scala:26)
	at io.gatling.core.structure.ScenarioBuilder.build(StructureBuilder.scala:51)
	at io.gatling.core.structure.PopulationBuilder.build(PopulationBuilder.scala:82)
	at io.gatling.core.scenario.SimulationParams.$anonfun$scenarios$1(Simulation.scala:191)
	at scala.collection.immutable.List.map(List.scala:286)
	at io.gatling.core.scenario.SimulationParams.scenarios(Simulation.scala:191)
	at io.gatling.app.Runner.run0(Runner.scala:91)
	at io.gatling.app.Runner.run(Runner.scala:60)
	at io.gatling.app.Gatling$.start(Gatling.scala:80)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:46)
	at io.gatling.app.Gatling$.main(Gatling.scala:38)
	at io.gatling.app.Gatling.main(Gatling.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.gatling.mojo.MainWithArgsInFile.runMain(MainWithArgsInFile.java:50)
	at io.gatling.mojo.MainWithArgsInFile.main(MainWithArgsInFile.java:33)
15:59:48.707 [DEBUG] i.n.u.i.NativeLibraryLoader - netty_tcnative_windows_x86_64 cannot be loaded from java.library.path, now try
how to resolve this

**Comment by ralphhuang** [comment]
JDK8+MAC os

osX  intel
`  <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative</artifactId>
      <version>2.0.61.Final</version>
      <classifier>osx-x86_64</classifier>
    </dependency>`

osX m1/m2
`  <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative</artifactId>
      <version>2.0.61.Final</version>
      <classifier>osx-aarch_64</classifier>
    </dependency>`

**Comment by Tianqi-Dotes** [comment]
I think upgrade or add netty-tcnative-boringssl-static can solve.
